apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-secret
  namespace: default
spec:
  encryptedData:
    foo: AgBtGSSJwZRU+zDMA8N/d93+ChdZGejvNONE4oWvHX7+yFbRDDtviG4v8qbAvtakRHhDJLeNJwpr45Hk1hgHCR6ikDgHVl3HPt41ARROk8LF62Up06DnJ6tK78Hhq9c1evW+Rj9qOXHrv7CdD/enu6PaqJLUy6+CvcTM4aD06+KMIoKp59cqdBaq95zR2dJRWUVvjJHGy0dmCH5fJLh8uzYaEUSHp3SNdaEKraUUSJqOC8l778gx5TkC+mFfoAuMMu0qun54at8dJNGL0VuEY2TdVoWD7yzIRisRkoH8etoWY9UiDZPKNgD11npzD+Z+ciFpZ9BTPLdN/r1LbPCGq3szrKaqc2SehOi73PZIURvswz76C//jmL0kFUnEhQEicidwpOYop9+3qRAWWGQQYlddTWj1+qCQxu2Tt1Fl3iWGVmyjYSAVfsmMUd78S9IUSZsmXC13NIsGnZX86Jncq+4tJJ3MoS7nWfubIf32AQbROXf9NVWIH+KTsTX6B261WBNK3G2pj9uybRlJDRF8/eFEzfr45R96N0RX5MgRSIpsBX5W6AlDzxArgXZ0mM9Qgla+Z+wgtehftt49NUJwHP1SF0M16FSeTbeHaTk9VpfXQIL2Zorcc5uesWGbs16Cr1WfiKUuH0v/usjsPu2og9G49BD3vBiicEnj5rE0gigjn06FlF/3PlBDH3o+xVzI6WXglaKo3t/i79g=
  template:
    metadata:
      creationTimestamp: null
      name: test-secret
      namespace: default

