apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  name: some-hook-secret
stringData:
  foo: bar 
---
apiVersion: v1
kind: Secret
metadata:
  name: some-nonhook-secret
stringData:
  bar: foo 

